### ISSUE TITLE
When run again, it creates another album of same name?

### ISSUE THREAD

**Issue by kaihendry** [robertoaloi/flickr-backup#2]

**Comment by robertoaloi** [comment]
Hi @kaihendry, yes, that is by design. I wanted the application to be less "destructive" as possible and using a new album for each session was the safest choice for me. This was to avoid situations where you have an old album containing some old photos with a given name (maybe a shared one) and getting an undesired mix of photos in the same album. Much better to create a new album. The worse that can happen is for you to have to manually delete old versions of the same album (which is a cheap and safe operation, since contained photos are never touched).

Closing this for now, but feel free to re-open it if you come out with a nicer idea.
